# Generated by Django 5.2.3 on 2025-06-14 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_heroslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
