# Generated by Django 5.2.3 on 2025-06-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
