# Generated by Django 5.2.3 on 2025-06-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfographicStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('icon', models.ImageField(upload_to='infographic/', verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Başvuru Süreci Adımı',
                'verbose_name_plural': 'Başvuru Süreci Adımları',
                'ordering': ['order'],
            },
        ),
    ]
