# Generated by Django 5.2.3 on 2025-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_infographicstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographicstep',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='infographicstep',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='infographicstep',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='infographicstep',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
