# Generated by Django 5.2.3 on 2025-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_infographicstep_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
