# Generated by Django 5.2.3 on 2025-06-19 13:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_heroslider_subtitle_en_heroslider_subtitle_tr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Başvuru', 'verbose_name_plural': 'Başvurular'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'SSS', 'verbose_name_plural': 'Sıkça Sorulan Sorular'},
        ),
        migrations.AlterModelOptions(
            name='heroslider',
            options={'verbose_name': 'Ana Slider', 'verbose_name_plural': 'Ana Sliderlar'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipprogram',
            options={'verbose_name': 'Burs Programı', 'verbose_name_plural': 'Burs Programları'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'verbose_name': 'Başarı Hikayesi', 'verbose_name_plural': 'Başarı Hikayeleri'},
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='application',
            name='identity_number',
            field=models.CharField(max_length=11, verbose_name='T.C. Kimlik No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='important_project_order',
            field=models.JSONField(verbose_name='Önemli Projeler Sıralaması'),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.TextField(verbose_name='Motivasyon'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_certificate',
            field=models.FileField(upload_to='applications/certificates/', verbose_name='Öğrenci Belgesi'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Cevap'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Soru'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='scholarship_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.scholarshipprogram', verbose_name='Burs Programı'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(upload_to='hero_sliders/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='image',
            field=models.ImageField(upload_to='scholarship_programs/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Etiket'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='profile_photo',
            field=models.ImageField(upload_to='basari_hikayeleri/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
