# Generated by Django 5.2.3 on 2025-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_application_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographicstep',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
