# Generated by Django 5.2.3 on 2025-06-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_infographicstep_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessStory',
        ),
    ]
