# Generated by Django 5.2.3 on 2025-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_faq_answer_en_faq_answer_tr_faq_question_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='identity_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='T.C. Kimlik No'),
        ),
    ]
