# Generated by Django 5.2.3 on 2025-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_application_identity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Tıklanabilir Link'),
        ),
    ]
