[phases.setup]
nixPkgs = ["python312", "gunicorn", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn burs_programi.wsgi:application --bind 0.0.0.0:$PORT"
